module Pirata
  module Category
    AUDIO               = "100"
      AUDIO_MUSIC       = "101"
      AUDIO_BOOKS       = "102"
      AUDIO_SOUND_CLIPS = "103"
      AUDIO_FLAC        = "104"
      AUDIO_OTHER       = "199"
      
    VIDEO               = "200"
      VID_MOVIES        = "201"
      VID_MOVIES_DVDR   = "202"
      VID_MUSIC_VIDEO   = "203"
      VID_MOVIE_CLIPS   = "204"
      VID_TV_SHOWS      = "205"
      VID_HANDHELD      = "206"
      VID_HD_MOVIES     = "207"
      VID_HD_TV_SHOWS   = "208"
      VID_3D            = "209"
      VID_OTHER         = "299"
      
    APPLICATIONS        = "300"
      APP_WINDOWS       = "301"
      APP_MAC           = "302"
      APP_UNIX          = "303"
      APP_HANDHELD      = "304"
      APP_IOS           = "305"
      APP_ANDROID       = "306"
      APP_OTHER_OS      = "399"
    
    GAMES               = "400"
      GAMES_PC          = "401"
      GAMES_MAC         = "402"
      GAMES_PSX         = "403"
      GAMES_XBOX        = "404"
      GAMES_WII         = "405"
      GAMES_HANDHELD    = "406"
      GAMES_IOS         = "407"
      GAMES_ANDROID     = "408"
      GAMES_OTHER       = "499"
    
    PORN                = "500"
      PORN_MOVIES       = "501"
      PORN_MOVIES_DVDR  = "502"
      PORN_PICTURES     = "503"
      PORN_GAMES        = "504"
      PORN_HD_MOVIES    = "505"
      PORN_MOVIE_CLIPS  = "506"
      PORN_OTHER        = "599"
      
    OTHER               = "600"
      EBOOKS            = "601"
      COMICS            = "602"
      PICTURES          = "603"
      COVERS            = "604"
      PHYSIBLES         = "605"
      OTHER_OTHER       = "699"
  end
end